In [1]:
import pandas as pd

In [3]:
URL = "https://raw.githubusercontent.com/plotly/datasets/master/winequality-red.csv"
df = pd.read_csv(URL)
df.shape

(1599, 12)

In [4]:
print(df.duplicated().sum()) # duplicatlar sonini ko'rish, 240 ta bor ekan

240

In [5]:
df = df.drop_duplicates() # duplicat bo'lganlar o'chirildi.

In [6]:
df.duplicated().sum() # dublicatlar soni 0 ta ga tushdi, yani muvaffaqqiyatli o'chirildi.

np.int64(0)

In [7]:
df.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,1359.000000,1359.000000,1359.000000,1359.000000,1359.000000,1359.000000,1359.000000,1359.000000,1359.000000,1359.000000,1359.000000,1359.000000
mean,8.310596,0.529478,0.272333,2.523400,0.088124,15.893304,46.825975,0.996709,3.309787,0.658705,10.432315,5.623252
std,1.736990,0.183031,0.195537,1.352314,0.049377,10.447270,33.408946,0.001869,0.155036,0.170667,1.082065,0.823578
min,4.600000,0.120000,0.000000,0.900000,0.012000,1.000000,6.000000,0.990070,2.740000,0.330000,8.400000,3.000000
25%,7.100000,0.390000,0.090000,1.900000,0.070000,7.000000,22.000000,0.995600,3.210000,0.550000,9.500000,5.000000
50%,7.900000,0.520000,0.260000,2.200000,0.079000,14.000000,38.000000,0.996700,3.310000,0.620000,10.200000,6.000000
75%,9.200000,0.640000,0.430000,2.600000,0.091000,21.000000,63.000000,0.997820,3.400000,0.730000,11.100000,6.000000
max,15.900000,1.580000,1.000000,15.500000,0.611000,72.000000,289.000000,1.003690,4.010000,2.000000,14.900000,8.000000

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1359 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1359 non-null   float64
 1   volatile acidity      1359 non-null   float64
 2   citric acid           1359 non-null   float64
 3   residual sugar        1359 non-null   float64
 4   chlorides             1359 non-null   float64
 5   free sulfur dioxide   1359 non-null   float64
 6   total sulfur dioxide  1359 non-null   float64
 7   density               1359 non-null   float64
 8   pH                    1359 non-null   float64
 9   sulphates             1359 non-null   float64
 10  alcohol               1359 non-null   float64
 11  quality               1359 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 138.0 KB

In [14]:
df['good'] = (df['quality'] >= 6).astype(int)
# bu yerda biz quality-si 6 va undan katta bo'lganlarini 1, qolganlarini esa 0 qilib oldik

In [15]:
X = df.drop(columns=['quality', 'good'])
y = df['good']
# bunda biz features va targetni ajratib olyapmiz

In [28]:
from sklearn.model_selection import train_test_split
# train va test qismlariga ajratib oldik.
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

In [29]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
# bu yerda DecisionTree va RandomForest modellari o'qitilyapti
dt = DecisionTreeClassifier(max_depth=5, random_state=42)
rf = RandomForestClassifier(max_depth=5, n_estimators=100, random_state=42)
dt.fit(X_train, y_train)
rf.fit(X_train, y_train)

RandomForestClassifier(max_depth=5, random_state=42)

In [31]:
from sklearn.model_selection import cross_val_score

# natijalarni chiqaramiz:
print(f"Decision Tree Train Accuracy: {dt.score(X_train, y_train):.4f}")
print(f"Decision Tree Test Accuracy: {dt.score(X_test, y_test):.4f}")
print(f"Decision Tree 5-Fold CV: {cross_val_score(dt, X, y, cv=5).mean():.4f}")

print("=======================================================")
print(f"Random Forest Train Accuracy: {rf.score(X_train, y_train):.4f}")
print(f"Random Forest Test Accuracy: {rf.score(X_test, y_test):.4f}")
print(f"Random Forest 5-Fold CV: {cross_val_score(rf, X, y, cv=5).mean():.4f}")

Decision Tree Train Accuracy: 0.8031
Decision Tree Test Accuracy: 0.6765
Decision Tree 5-Fold CV: 0.6858
=======================================================
Random Forest Train Accuracy: 0.8123
Random Forest Test Accuracy: 0.7647
Random Forest 5-Fold CV: 0.7351

In [32]:
# ===========================================================================
# YANGI DATASET USTIDA BAJARAMIZ: HEART DISEASE DATASET
# ===========================================================================

In [43]:
import pandas as pd

URL_HEART = "https://raw.githubusercontent.com/kb22/Heart-Disease-Prediction/master/dataset.csv"
df_h = pd.read_csv(URL_HEART)
df_h.shape

(303, 14)

In [44]:
df_h.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [45]:
print(df_h.duplicated().sum()) # duplicat bo'lgan qiymatlar 240 ta bor ekan, bularni o'chiramiz

1

In [46]:
df_h = df_h.drop_duplicates() # duplicat bo'lgan qiymatlar o'chirildi.

In [47]:
df_h.isnull().sum() # bo'sh qiymatlar yo'q ekan, bu yaxshi

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [48]:
df_h.info() # bu datasetda hammasi float va int bo'lganligi uchun, type conversion qilishimiz kerak emas! nice!

<class 'pandas.core.frame.DataFrame'>
Index: 302 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       302 non-null    int64
 1   sex       302 non-null    int64
 2   cp        302 non-null    int64
 3   trestbps  302 non-null    int64
 4   chol      302 non-null    int64
 5   fbs       302 non-null    int64
 6   restecg   302 non-null    int64
 7   thalach   302 non-null    int64
 8   exang     302 non-null    int64
 9   oldpeak   302 non-null    float64
 10  slope     302 non-null    int64
 11  ca        302 non-null    int64
 12  thal      302 non-null    int64
 13  target    302 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 35.4 KB

In [49]:
from sklearn.model_selection import train_test_split
# target ni aniqlab uni drop qildik
X = df_h.drop(columns=['target'])
y = df_h['target']
# datani train va test qismlarga bo'lib oldik
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [50]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

# modellarni o'qitish jarayoni
dt = DecisionTreeClassifier(max_depth=5, random_state=42)
rf = RandomForestClassifier(max_depth=5, n_estimators=100, random_state=42)
dt.fit(X_train, y_train)
rf.fit(X_train, y_train)

RandomForestClassifier(max_depth=5, random_state=42)

In [54]:
from sklearn.model_selection import cross_val_score

print(f"Decision Tree Train Accuracy: {dt.score(X_train, y_train):.4f}")
print(f"Decision Tree Test Accuracy: {dt.score(X_test, y_test):.4f}")
print(f"Decision Tree 5-Fold CV: {cross_val_score(dt, X, y, cv=5).mean():.4f}")

print("=======================================================")
print(f"Random Forest Train Accuracy: {rf.score(X_train, y_train)}")
print(f"Random Forest Test Accuracy: {rf.score(X_test, y_test)}")
print(f"Random Forest 5-Fold CV: {cross_val_score(rf, X, y, cv=5).mean():.4f}")

# random forest train accuracy-si decision tree-dan kattaroq.
# lekin test accuracy decision tree-da yaxshiroq natija ko'rsatdi.
# CV esa random forest-da yaxshiroq chiqdi.

Decision Tree Train Accuracy: 0.9253
Decision Tree Test Accuracy: 0.8197
Decision Tree 5-Fold CV: 0.7780
=======================================================
Random Forest Train Accuracy: 0.946058091286307
Random Forest Test Accuracy: 0.8032786885245902
Random Forest 5-Fold CV: 0.8443

In [61]:
imp1 = pd.Series(rf.feature_importances_, index=X.columns)
top_3 = imp1.sort_values(ascending=False).head(3)
print("Random forest eng muhim 3 ta belgi:")
print(top_3.round(4))
# random forest max_features parametri hisobiga, bo'lingan vaqti hammasini emas
# faqat tasodify kichik guruhlarni belgilaydi. shu sababli kuchsizroq belgilar ham bo'linishda qatnashib
# importance da muvozanatli taqsimlanadi.

imp2 = pd.Series(dt.feature_importances_, index=X.columns)
top_3 = imp2.sort_values(ascending=False).head(3)
print("Decision tree eng muhim 3 ta belgi:")
print(top_3)
# decision tree-da bitta daraxt bo'lganligi uchun, barcha ustunlar ichida eng
# kuchlilarini tanlaydi va uni ildizga qo'yadi. natijada butun model shunga haddan
# tashqari bog'lanib qoladi

Random forest eng muhim 3 ta belgi:
cp         0.1826
thal       0.1331
oldpeak    0.1221
dtype: float64
Decision tree eng muhim 3 ta belgi:
cp         0.391480
oldpeak    0.176852
thal       0.116071
dtype: float64